# define a default docker image for all jobs
image: node:latest

stages:
  #- install  # install all npm dependencies
  #- test     # execute unit tests
  #- qaCreate # create the statk from stack for QA
  #- qaTest   # test on the QA stack
  #- qaRemove # remove the QA stack
  - deploy   # stage for deploying to enviroments

cache:
  paths:
    - node_modules/


#install:npm:
#  stage: install
#  script:
#    - make install

#test:lint:
#  stage: test
#  script:
#    - npm install -g standard
#    - standard

deploy:development:
  stage: deploy
  script:
    - make deploy
  only:
    - master
  environment: development

deploy:production:
  stage: deploy
  script:
    - make deploy STAGE=prd
  when: manual
  only:
    - master
  environment: production
