service: owlflow-hooks

frameworkVersion: ">=2.0.0 <3.0.0"

plugins:
  - serverless-domain-manager

custom:
  defaultStage: dev
  currentStage: ${opt:stage, self:custom.defaultStage}
  resourcesPrefix: ${self:service}-${self:custom.currentStage}
  config: ${file(./config.${self:custom.currentStage}.json)}
  deploymentBucket: ${self:custom.config.DEPLOYMENT_BUCKET}
  customDomain:
    domainName: ${self:custom.config.CUSTOM_API_HOST}
    certificateName: ${self:custom.config.ACM_CERTIFICATE_NAME}
    basePath: 'v1'
    stage: ${self:provider.stage}
    createRoute53Record: false
    endpointType: 'regional'

provider:
  name: aws
  runtime: nodejs10.x
  stage: ${self:custom.currentStage}
  region: ${self:custom.config.REGION}
  timeout: 30
  logRetentionInDays: 14
  endpointType: regional
  deploymentBucket:
    name: ${self:custom.deploymentBucket}-${self:provider.region}
  environment:
    SERVERLESS_REGION: ${self:custom.config.REGION}

package:
  excludeDevDependencies: true
  individually: false
  exclude:
    - node_modules/**
    - .eslintrc.js
    - .gitattributes
    - .gitignore
    - .git/**
    - .npmrc
    - .babelrc
    - README.md
    - serverless.yml

functions:
  status:
    handler: handler.status
    name: ${self:custom.resourcesPrefix}-status
    events:
      - http:
          path: /status
          method: get

# Create our resources with separate CloudFormation templates
resources:
  # API Gateway
  - ${file(resources/api-gateway.yml)}
