service: owlflow-hooks

frameworkVersion: ">=2.0.0 <3.0.0"

custom:
  defaultStage: dev
  defaultRegion: us-east-1
  currentStage: ${opt:stage, self:custom.defaultStage}
  currentRegion: ${opt:region, self:custom.defaultRegion}
  resourcesPrefix: ${self:service}-${self:custom.currentStage}
  config: ${file(./config.${self:custom.currentStage}.json)}
  deploymentBucket: ${self:custom.config.DEPLOYMENT_BUCKET}

provider:
  name: aws
  runtime: nodejs12.x
  stage: ${self:custom.currentStage}
  region: ${self:custom.currentRegion}
  timeout: 30
  logRetentionInDays: 14
  endpointType: regional
  deploymentBucket:
    name: ${self:custom.deploymentBucket}-${self:provider.region}
  environment:
    SERVERLESS_REGION: ${self:custom.config.REGION}

layers:
  commonLibs:
    path: layer/commonLibs
    name: ${self:custom.resourcesPrefix}-commonLibs
    compatibleRuntimes:
      - nodejs12.x
    retain: true

package:
  excludeDevDependencies: true
  individually: false
  exclude:
    - node_modules/**
    - .eslintrc.js
    - .gitattributes
    - .gitignore
    - .git/**
    - .npmrc
    - .babelrc
    - README.md
    - serverless.yml

functions:
  status:
    handler: handler.status
    name: ${self:custom.resourcesPrefix}-status
    events:
      - http:
          path: /status
          method: get

# Create our resources with separate CloudFormation templates
resources:
  # API Gateway
  - ${file(resources/api-gateway.yml)}

  # Event Bus
  - ${file(resources/event-bus.yml)}

